'use strict';
// Standalone frontend: no Firebase or Sahana's code is needed.
const $ = id => document.getElementById(id);
const categories = ['Electronics','Documents','Accessories','Books','Clothing','Keys','Bags','Other'];
const icons = {Electronics:'📱',Documents:'📄',Accessories:'👛',Books:'📚',Clothing:'👕',Keys:'🔑',Bags:'🎒',Other:'📦'};
const storageKey = 'campusLostFoundItems'; // Compatible with the earlier frontend.
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const samples = [
{id:'demo-wallet',type:'lost',name:'Black Wallet',category:'Accessories',description:'Black leather wallet with a college ID inside. Sample report for the frontend demo.',location:'Library',date:today(),contact:'Demo report — replace with your own contact',contactName:'Sample reporter',imageURL:'',status:'active'},
{id:'demo-bottle',type:'found',name:'Blue Water Bottle',category:'Other',description:'Blue water bottle found near Block C. Sample report for the frontend demo.',location:'Block C',date:today(),contact:'Demo report — replace with your own contact',contactName:'Sample reporter',imageURL:'',status:'active'},
{id:'demo-calculator',type:'lost',name:'Calculator',category:'Electronics',description:'Black scientific calculator misplaced near the CS Block. Sample report for the frontend demo.',location:'CS Block',date:today(),contact:'Demo report — replace with your own contact',contactName:'Sample reporter',imageURL:'',status:'active'}];
let items = samples.map(item => ({...item}));
let storageWarning = '';
try { const saved = localStorage.getItem(storageKey); if(saved !== null){const parsed=JSON.parse(saved);if(!Array.isArray(parsed))throw new Error('Invalid saved data'); items=parsed.filter(item=>item && typeof item==='object' && ['lost','found'].includes(item.type)).map(item=>({...item,id:String(item.id),name:String(item.name||'Unnamed item'),category:String(item.category||'Other'),description:String(item.description||''),location:String(item.location||''),date:String(item.date||''),contact:String(item.contact||''),imageURL:String(item.imageURL||'')}));} } catch(error){storageWarning='Saved data could not be loaded. Showing sample reports.';}
function text(tag,content,className){const el=document.createElement(tag);el.textContent=content;if(className)el.className=className;return el;}
function option(select,value,label){const el=text('option',label);el.value=value;select.append(el);}
for(const category of categories){option($('categoryFilter'),category,category);option($('itemCategory'),category,category);}
function imageURL(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:'';}catch{return '';}}
function photo(item,className){const wrapper=document.createElement('div');wrapper.className=className;const fallback=text('div',icons[item.category]||'📦','placeholder');wrapper.append(fallback);const url=imageURL(item.imageURL);if(url){const img=new Image();img.alt=item.name;img.loading='lazy';img.referrerPolicy='no-referrer';img.hidden=true;img.addEventListener('load',()=>{fallback.hidden=true;img.hidden=false;});img.addEventListener('error',()=>{img.remove();fallback.title='Image unavailable. Check the direct image URL.';});img.src=url;wrapper.append(img);}return wrapper;}
function formatDate(value){const d=new Date(value+'T00:00:00');return Number.isNaN(d.getTime())?'Date unavailable':d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});}
function refreshLocations(){const current=$('locationFilter').value;$('locationFilter').replaceChildren();option($('locationFilter'),'all','All Locations');[...new Set(items.map(x=>x.location).filter(Boolean))].sort().forEach(location=>option($('locationFilter'),location,location));$('locationFilter').value=[...$('locationFilter').options].some(x=>x.value===current)?current:'all';}
function stats(){const counts=[['Total Reports',items.length,'▤'],['Lost Items',items.filter(x=>x.type==='lost').length,'△'],['Found Items',items.filter(x=>x.type==='found').length,'♧'],['Returned Items',items.filter(x=>x.status==='returned').length,'✓']];$('stats').replaceChildren();counts.forEach(([label,count,icon])=>{const el=text('div','','stat');el.append(text('span',icon,'stat-icon'));const body=document.createElement('div');body.append(text('strong',count),text('small',label));el.append(body);$('stats').append(el);});}
function render(){const keyword=$('search').value.trim().toLowerCase();const range=$('dateFilter').value;const day=new Date(today()+'T00:00:00').getTime();const filtered=items.filter(item=>{const itemDay=new Date(item.date+'T00:00:00').getTime();const age=Math.round((day-itemDay)/86400000);return [item.name,item.description,item.location,item.category].some(v=>v.toLowerCase().includes(keyword))&&($('typeFilter').value==='all'||item.type===$('typeFilter').value)&&($('categoryFilter').value==='all'||item.category===$('categoryFilter').value)&&($('locationFilter').value==='all'||item.location===$('locationFilter').value)&&(range==='all'||(range==='today'?age===0:age>=0&&age<Number(range)));});$('itemsContainer').replaceChildren();$('empty').hidden=filtered.length!==0;$('results').textContent=`${filtered.length} ${filtered.length===1?'item':'items'} shown`;filtered.forEach(item=>{const card=text('article','','item-card');const visual=photo(item,'item-image');visual.append(text('span',item.type==='lost'?'LOST':'FOUND','badge '+item.type));const body=text('div','','item-content');body.append(text('span',item.category,'category'),text('h3',item.name),text('p',item.description,'description'));const meta=text('div','','item-meta');meta.append(text('span','⌖ '+item.location),text('span',formatDate(item.date)));const btn=text('button','View Details →','view-btn');btn.type='button';btn.addEventListener('click',()=>openDetails(item));body.append(meta,btn);card.append(visual,body);$('itemsContainer').append(card);});}
function openDetails(item){const body=$('modalBody');body.replaceChildren();const visual=photo(item,'item-image modal-image');body.append(visual,text('span',item.type==='lost'?'Lost Item':'Found Item','badge '+item.type),text('h2',item.name),text('p',item.description,'modal-description'));const details=text('div','','modal-details');[['Category',item.category],['Location',item.location],['Date',formatDate(item.date)],['Time',item.time],['Contact Name',item.contactName],['Contact',item.contact],['Status',item.status==='returned'?'Returned':'Active']].forEach(([label,value])=>{if(!value)return;const row=document.createElement('p');row.append(text('strong',label+': '));if(label==='Contact'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)){const link=text('a',value);link.href='mailto:'+value;row.append(link);}else if(label==='Contact'&&/^\+?[\d\s()-]{7,20}$/.test(value)){const link=text('a',value);link.href='tel:'+value.replace(/[^+\d]/g,'');row.append(link);}else row.append(document.createTextNode(value));details.append(row);});body.append(details);$('itemModal').showModal();document.body.style.overflow='hidden';}
$('modalClose').addEventListener('click',()=>$('itemModal').close());$('itemModal').addEventListener('close',()=>{document.body.style.overflow='';});$('itemModal').addEventListener('click',event=>{if(event.target===$('itemModal')){const r=$('itemModal').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('itemModal').close();}});
let toastTimer;function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4000);}
let previewTimer;let previewVersion=0;$('imageURL').addEventListener('input',()=>{clearTimeout(previewTimer);const version=++previewVersion;const raw=$('imageURL').value.trim();$('previewBox').hidden=!raw;$('preview').hidden=true;$('previewMessage').textContent='Loading image preview…';previewTimer=setTimeout(()=>{if(version!==previewVersion)return;const url=imageURL(raw);if(!url){$('previewMessage').textContent='Use a valid http or https image URL.';return;}const probe=new Image();probe.referrerPolicy='no-referrer';probe.onload=()=>{if(version!==previewVersion)return;$('preview').src=url;$('preview').hidden=false;$('previewMessage').textContent='This image will appear on your report.';};probe.onerror=()=>{if(version!==previewVersion)return;$('previewMessage').textContent='Could not load this image. Use a publicly accessible direct image URL.';};probe.src=url;},250);});
$('reportForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));for(const key of Object.keys(values))values[key]=values[key].trim();$('formError').textContent='';if(['name','category','description','location','date','contactName','contact'].some(key=>!values[key])){$('formError').textContent='Please complete every required field.';return;}if(values.date>today()){$('formError').textContent='Choose today or an earlier date.';return;}if(values.imageURL&&!imageURL(values.imageURL)){$('formError').textContent='Use a valid http or https image URL.';return;}const item={...values,id:globalThis.crypto?.randomUUID?.()||String(Date.now()),status:'active'};const next=[item,...items];try{localStorage.setItem(storageKey,JSON.stringify(next));}catch(error){$('formError').textContent='Your browser could not save the report. Allow local storage or free some browser storage, then try again.';return;}items=next;form.reset();form.elements.date.value=today();$('previewBox').hidden=true;previewVersion++;$('filters').reset();refreshLocations();stats();render();location.hash='#/browse';toast('Your item was reported successfully!');});
$('filters').addEventListener('submit',event=>event.preventDefault());['search','typeFilter','categoryFilter','locationFilter','dateFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('filters').addEventListener('reset',()=>setTimeout(render,0));
const steps=[['Report','Post details and an image URL of your lost or found item. It takes less than a minute.'],['Search','Browse listings and use filters to find possible matches by category, location or keywords.'],['Reunite','Contact the person who posted the item and verify ownership before returning it.']];['homeSteps','howSteps'].forEach(id=>steps.forEach(([title,description],index)=>{const step=text('div','','step');step.append(text('div',index+1,'step-number'),text('h3',title),text('p',description));$(id).append(step);}));
function route(){const hash=location.hash||'#/';const path=hash.split('?')[0];const report=path==='#/report',how=path==='#/how-it-works',browse=path==='#/browse';$('homeHero').hidden=report||how||browse;$('browsePage').hidden=report||how;$('reportPage').hidden=!report;$('howPage').hidden=!how;$('browseHeading').hidden=!browse;$('homeSteps').hidden=browse;$('listingTitle').textContent=browse?'All Listings':'Recent Listings';if(report){const type=new URLSearchParams(hash.split('?')[1]||'').get('type');if(['lost','found'].includes(type))$('reportForm').elements.type.value=type;}document.querySelectorAll('#navLinks a').forEach(a=>{const active=a.getAttribute('href')===path;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('navLinks').classList.remove('open');$('menu').setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'instant'});}
$('menu').addEventListener('click',()=>{$('navLinks').classList.toggle('open');$('menu').setAttribute('aria-expanded',String($('navLinks').classList.contains('open')));});window.addEventListener('hashchange',route);$('reportForm').elements.date.max=today();$('reportForm').elements.date.value=today();refreshLocations();stats();render();route();if(storageWarning)toast(storageWarning);
